base.path: /api/v1
verify.mutant.path: /mutant
stats.path: /stats
spring.data.mongodb.uri: mongodb+srv://admin:Admin*123@cluster0-zq7im.mongodb.net/test?retryWrites=true&w=majority&connectTimeoutMS=30000&socketTimeoutMS=30000
spring.data.mongodb.database: test
server.port: 8081
http.headers: Content-type:application/json; charset=utf-8,X-Permitted-Cross-Domain-Policies:none,X-Frame-Options:DENY,Cache-Control:no-store; no-store; max-age:0; must-revalidate,content-security-policy:default-src 'self'; frame-ancestors 'none'; reflected-xss block,Pragma:no-cache,Strict-Transport-Security:max-age:31536000; includeSubDomains,X-XSS-Protection:1; mode:block,X-Content-Type-Options:nosniff